// src/components/Projects/projectsData.js

export const allProjects = [
  {
    id: 1,
    title: "Buds Studio E-Commerce",
    type: "website",
    category: "freelance",
    date: "August 2025 - September 2025",
    desc: "An e-commerce website built to manage product catalogs, orders, and customer reviews. Developed as a fullstack project with a modern UI design.",
    tech: ["Laravel", "Blade", "TailwindCSS", "MySQL", "Alpine.js"],
    link: "https://github.com/pendragonnn/buds-studio-ecommerce-website",
  },
  {
    id: 2,
    title: "Quran App",
    type: "mobileapp",
    category: "private project",
    date: "July 2025",
    desc: "A simple Quran reading app built with Flutter, providing offline access, surah list, and customizable theme settings.",
    tech: ["Flutter", "Dart", "GetX", "SQLite"],
    link: "https://github.com/pendragonnn/Quran-App-Flutter",
  },
  {
    id: 3,
    title: "Book Rent App",
    type: "website",
    category: "freelance",
    date: "July 2025 - August 2025",
    desc: "A web-based book rental management system featuring book catalog, user dashboard, and admin control panel.",
    tech: ["Laravel", "Blade", "TailwindCSS", "MySQL"],
    link: "https://github.com/pendragonnn/book-rent-app",
  },
  {
    id: 4,
    title: "PalmGuard",
    type: "mobileapp",
    category: "thesis",
    date: "January 2025 - July 2025",
    desc: "A mobile app designed to detect and manage brown spot disease on palm oil leaves using machine learning and image analysis.",
    tech: ["TensorFlow", "Python", "Kotlin", "XML", "Android Studio", "SQLite"],
    link: "https://drive.google.com/drive/folders/1rpGlSzVu0cIHGEugy-JjRBVWo0DwUcNf?usp=sharing",
  },
  {
    id: 5,
    title: "Dream Vault",
    type: "mobileapp",
    category: "private project",
    date: "February 2025",
    desc: "A mobile app for recording and analyzing dreams, built to explore journaling and pattern tracking.",
    tech: ["Kotlin", "XML", "SQLite"],
    link: "https://drive.google.com/drive/folders/1pywVC5So8vozLpaf5Tli0pCA_Ank0WNu?usp=sharing",
  },
  {
    id: 6,
    title: "The News App",
    type: "mobileapp",
    category: "private project",
    date: "February 2025",
    desc: "A mobile app that fetches and displays live news articles using a public API, with category filters and offline mode support.",
    tech: ["Kotlin", "XML", "Retrofit", "Room Database"],
    link: "https://drive.google.com/drive/folders/1WlN0zWAdNrVGqpMMWjFcvs1Sil36kPva?usp=sharing",
  },
  {
    id: 7,
    title: "TeaGuard",
    type: "mobileapp",
    category: "funded project",
    date: "May 2024 - July 2024",
    desc: "A machine learning-based Android app for detecting pests and diseases in tea plants. Developed as part of a national research grant (PKM-KC).",
    tech: ["TensorFlow", "Python", "Kotlin", "XML", "Android Studio", "PostgreSQL", "Express", "Retrofit"],
    link: "https://drive.google.com/drive/folders/14K88KOR7dhpg61kihzGr0BnjpejzmLO6?usp=sharing",
  },
  {
    id: 8,
    title: "Qwords Landing Page Redesign",
    company: "Qwords x Rakamin Academy",
    type: "website",
    category: "virtual internship",
    date: "December 2023 – January 2024",
    desc: "Redesigned and rebuilt the landing page for Qwords during a project-based virtual internship, focusing on performance and clean UI.",
    tech: ["Laravel", "React", "InertiaJs", "TailwindCSS"],
    link: "https://final-task-qwords-pbi-demo-version.vercel.app/",
  },
  {
    id: 9,
    title: "Mini Movie Library",
    type: "website",
    category: "private project",
    date: "December 2023",
    desc: "A small web app displaying movies from TMDb API with a random movie picker and responsive layout for smooth user experience.",
    tech: ["NextJs", "React-Bootstrap"],
    link: "https://mini-movie-library.vercel.app/",
  },
  {
    id: 10,
    title: "E-Commerce Catalog",
    company: "Core Initiative x Rakamin Academy",
    type: "website",
    category: "virtual internship",
    date: "October 2023 – December 2023",
    desc: "Built an online catalog that fetches products from API (FakeStoreAPI) during a Frontend Developer virtual internship.",
    tech: ["VueJs", "CSS"],
    link: "https://ecommerce-catalog-three.vercel.app/",
  },
  {
    id: 11,
    title: "ShoeStock – Inventory Web",
    company: "Rakamin Academy Bootcamp Final Project",
    type: "website",
    category: "final task bootcamp",
    date: "October 2023 – November 2023",
    desc: "Led a team of 7 to build a web-based inventory management system for shoes as part of Rakamin’s Fullstack Bootcamp final project.",
    tech: ["ExpressJs", "NextJs", "TailwindCSS", "PostgreSQL"],
    link: "https://github.com/pendragonnn/final-project-inventory-web",
  },
];
